all: clean compile
	@echo -e '[INFO] Done!'

clean:
	@echo -e '[INFO] Cleaning class files'
	@rm -rf  ./cs/cs430/lab4/DatabaseAccess.class
	@rm -rf  ./cs/cs430/lab4/Lab5Utils.class
	@rm -rf  ./cs/cs430/lab4/MemberDetails.class

compile:

	@echo -e '[INFO] Compiling Sources'
	@javac -d . ./src/cs/cs430/lab4/Lab5Utils.java
	@javac -d . ./src/cs/cs430/lab4/DatabaseAccess.java
	@javac -d . ./src/cs/cs430/lab4/MemberDetails.java
